version: '3'
services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        DOMAIN: $DOMAIN
        CREDENTIAL: $CREDENTIAL
        WEB_ROOT: $WEB_ROOT
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - .docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - .docker/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    command:
      bash -c "cp -f /etc/mysql/my.cnf.tmp /etc/mysql/my.cnf && mysqld"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - .docker/my.cnf:/etc/mysql/my.cnf.tmp
volumes:
  mysql_data:
